name: Site

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.ts
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install prettier

      - name: Format code
        run: npm run format

      - name: Build project
        run: npm run build --base=/landing/

      - name: Archive production artifacts
        run: cd dist && zip -r ../site.zip . && cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: site.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
